config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/about' => 'welcome#about'

  #renders the club w/ the most books
  #poppin
  #routes => controller (club) => club model (scope method) => controller => view file
  get '/poppin' => 'clubs#poppin'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  # 'omniauth' name comes from omniauth_controller.rb

  resources :users, only: [:show]
  resources :comments, except: [:show, :index]
  resources :books

  resources :clubs, except: [:destroy] do
    resources :books, only: [:index, :new, :create]
  end

  resources :books do 
    resources :comments, only: [:index, :new, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/club.rb
class Club < ApplicationRecord
    has_many :books
    has_many :users, through: :books

    validates :name, presence: true, uniqueness: true

    #scope method => render the club w/ the MOST books
    #order by books, make sure it's from max to min, limit to 1
    scope :most_books, -> { joins(:books).group("books.club_id").order("count(books.club_id) desc").limit(1) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :omniauthable, omniauth_providers: [:google_oauth2]
 
    has_many :comments
    has_many :books
    has_many :clubs, through: :books
    
    # validates :name, :username, presence: true
    # validates :username, uniqueness: true
    #devise gem helps validate your password
  
    def self.create_from_provider_data(provider_data)
      where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
        user.email = provider_data.info.email
        user.password = Devise.friendly_token[0, 20]
      end
    end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    before_action :set_club, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index]

    #in the view, shows me edit link if current user is a part of the club
    before_action :set_club_ids, only: [:show, :edit]
    
    def index
        @clubs = Club.all
    end

    def show
        if Club.find_by(id: params[:id])
            @club = Club.find(params[:id])
        else
            redirect_to clubs_path, alert: "Could not find club"
        end
    end

    def new
        @club = Club.new
    end

    def create
        @club = Club.new(club_params)

        if @club.save
            redirect_to club_path(@club)
        else
            render :new
        end
    end

    def edit        
        if !@club_ids.include?(@club.id)
            redirect_to clubs_path, alert: "You can't edit this club unless you're a part of it..."
        end
    end

    def update
        if @club.update(club_params)
            redirect_to club_path(@club)
        else
            render :edit
        end
    end

    def poppin
        #call on the scope method
        @club = Club.most_books[0]
    end

    # Don't want users to be able to destroy clubs
    # def destroy
    #     if @club.books.empty?
    #         @club.destroy
    #         redirect_to clubs_path
    #     else
    #         redirect_to clubs_path, alert: "Please remove all the books before deleting this club"
    #     end
    # end

    private

    def club_params
        params.require(:club).permit(:name)
    end

    def set_club
        @club = Club.find(params[:id])
    end

    def set_club_ids
        @club_ids = current_user.books.collect{|book| book.club_id}.uniq
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<%= form_with model: club do |f| %>

    <% if club.errors.any? %>
        <div id="error_explanation">
            <h2>There were some errors:</h2>
            <ul>
                <% club.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field<%= ' field_with_errors' if club.errors[:name].any? %>">
        <%= f.label :name %><br>
        <%= f.text_field :name %><br><br>
    </div>

    <%= f.submit %>
<% end %>

app/views/clubs/edit.html.erb
<h1>Edit an existing book club:</h1>

<%= render partial: 'form', locals: {club: @club} %>

app/views/clubs/index.html.erb
<h1>See all the BookClubs:</h1>

<%= render 'layouts/flash' %>

<br>

<ul>
<% @clubs.collect do |club| %>
        <li><%= link_to club.name, club_path(club) %> (# of users: <%= club.users.uniq.count %>)</li>
<% end %>
</ul>

<br>

<% if user_signed_in? %>
        <%= link_to "Create a new Book Club", new_club_path %>
<% end %>

app/views/clubs/new.html.erb
<h1>Create a new club:</h1>

<%= render partial: 'form', locals: {club: @club} %>

app/views/clubs/poppin.html.erb
<%= @club.name %>

app/views/clubs/show.html.erb
<h1>Welcome to <%= @club.name %></h1><br>

See the books we are reading: <br>
<ul>
<% @club.books.each do |book| %>
    <li>
        <%= link_to book.title, book_path(book) %> <em>(added by <%= book.user.email %>)</em>
    </li>
<% end %>
</ul>
<br>

See who is a part of our Book Club: <br>
<ul>
<% @club.users.uniq.each do |user| %>
    <li>
        <%= user.email %>
    </li>
<% end %>
</ul>

<% if @club_ids.include?(@club.id) %>
    <%= link_to "Edit Book Club", edit_club_path(@club) %><br>
<% end %>
<%= link_to "Add a Book To Join This Club", new_club_book_path(@club) %><br>

<!-- Don't want users to be able to delete clubs without having an club owner attribute-->
<!-- <% button_to "Delete This Club", club_path(@club), method: :delete %> -->