config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/about' => 'welcome#about'

  #renders the club w/ the most books
  #poppin
  #routes => controller (club) => club model (scope method) => controller => view file
  get '/poppin' => 'clubs#poppin'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  # 'omniauth' name comes from omniauth_controller.rb

  resources :users, only: [:show]
  resources :comments, except: [:show, :index]
  resources :books

  resources :clubs, except: [:destroy] do
    resources :books, only: [:index, :new, :create]
  end

  resources :books do 
    resources :comments, only: [:index, :new, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :omniauthable, omniauth_providers: [:google_oauth2]
 
    has_many :comments
    has_many :books
    has_many :clubs, through: :books
    
    # validates :name, :username, presence: true
    # validates :username, uniqueness: true
    #devise gem helps validate your password
  
    def self.create_from_provider_data(provider_data)
      where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
        user.email = provider_data.info.email
        user.password = Devise.friendly_token[0, 20]
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController    
    def show
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>