config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/about' => 'welcome#about'

  #renders the club w/ the most books
  #poppin
  #routes => controller (club) => club model (scope method) => controller => view file
  get '/poppin' => 'clubs#poppin'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  # 'omniauth' name comes from omniauth_controller.rb

  resources :users, only: [:show]
  resources :comments, except: [:show, :index]
  resources :books

  resources :clubs, except: [:destroy] do
    resources :books, only: [:index, :new, :create]
  end

  resources :books do 
    resources :comments, only: [:index, :new, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :club
  has_many :comments

  validates :title, :author, :summary, presence: true
  #validates :summary, length: { minimum: 25 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:edit, :update, :destroy]
    before_action :authenticate_user!
    
    def index
        # if I'm accessing this via the nested /clubs/:club_id/books
        if params[:club_id]
            # if the club is found
            if Club.find_by(id: params[:club_id])
                # show all of the club's books
                @books = Club.find(params[:club_id]).books
            # else if the club is NOT found
            else
                redirect_to clubs_path, alert: "Could not find club"
            end
        # if I'm accessing this via the non-nested root /books
        else 
            # show ALL of the books
            @books = Book.all
        end
    end

    def show
        if Book.find_by(id: params[:id])
            @book = Book.find(params[:id])
            @comments = @book.comments.comment_order
        else
            redirect_to books_path, alert: "Could not find book"
        end
    end

    def new
        # if I'm accessing this via a nested route and if club is found, @club will be defined
        if params[:club_id] && @club = Club.find_by(id: params[:club_id])
            # create a new book w/ a club association
            @book = Book.new(club_id: @club.id)
        else
            redirect_to clubs_path, alert: "You can't create a book without a club...nice try though 👀"
        end
    end

    def create
        @club = Club.find_by(id: params[:club_id])
        @book = Book.new(book_params)

        if @book.save
            redirect_to book_path(@book)
        else
            render :new
        end
    end

    def edit
        if @book.user_id != current_user.id
            redirect_to book_path(@book), alert: "You cannot edit this book..."
        end
    end

    def update
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            render :edit
        end
    end

    def destroy
        if @book.user_id == current_user.id
            @book.destroy
            redirect_to books_path
        else
            redirect_to books_path, alert: "You cannot delete this book..."
        end
    end

    private

    def book_params
        params.require(:book).permit(:title, :author, :summary, :club_id, :user_id)
    end

    def set_book
        @book = Book.find(params[:id])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<% # Defining @club allows form_with to recognize that it's from a nested route %>

<%= form_with model: [club, book] do |f| %>
    <% if book.errors.any? %>
        <div id="error_explanation">
            <h2>There were some errors:</h2>
            <ul>
                <% book.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <% if club %>
        <%= f.hidden_field :club_id, value: club.id %>
    <% end %>

    <div class="field<%= ' field_with_errors' if book.errors[:title].any? %>">
        <%= f.label :title %><br>
        <%= f.text_field :title %><br><br>
    </div>

    <div class="field<%= ' field_with_errors' if book.errors[:author].any? %>">
        <%= f.label :author %><br>
        <%= f.text_field :author %><br><br>
    </div>

    <div class="field<%= ' field_with_errors' if book.errors[:summary].any? %>">
        <%= f.label :summary %><br>
        <%= f.text_area :summary %><br><br>
    </div>

    <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit existing book:</h1>

<%= render partial: 'form', locals: {club: @club, book: @book} %>

app/views/books/index.html.erb
<h1>See what our users are reading:</h1>

<%= render 'layouts/flash' %>

<ul>
<% @books.each do |book| %>
    <li>
        <%= link_to book.title, book_path(book) %>
    </li>
<% end %>
</ul>

app/views/books/new.html.erb
<h1>Add a new book:</h1>

<%= render partial: 'form', locals: {club: @club, book: @book} %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1> 

<%= render 'layouts/flash' %>

<p>By <%= @book.author %></p>

<p><%= @book.summary %></p>

<p>Comments:</p>
<ul>
    <% @comments.each do |comment| %>
        <li>
            <%= comment.user.email %> says <%= comment.content %><br>
            <em>Posted at <%= comment_timestamp(comment) %></em><br>
            <% if comment.user_id == current_user.id %>
                <%= link_to "edit", edit_comment_path(comment) %> | <%= link_to "delete", comment_path(comment), method: :delete %><br>
            <% end %>
        </li>
    <% end %>
</ul>

<%= link_to "New Comment", new_book_comment_path(@book.id) %>


<br><br>
<% if current_user.id == @book.user_id %>
    <%= link_to "Edit this book", edit_book_path(@book.id) %><br>
    <%= button_to "Delete This Book", book_path(@book), method: :delete %><br>
<% end %>

<%= link_to "Go to book club page", club_path(@book.club_id) %><br>
<%= link_to "Interested in buying this book?", "http://www.google.de/search?q=#{@book.title}", :target => "_blank" %><br>