config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/about' => 'welcome#about'

  #renders the club w/ the most books
  #poppin
  #routes => controller (club) => club model (scope method) => controller => view file
  get '/poppin' => 'clubs#poppin'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  # 'omniauth' name comes from omniauth_controller.rb

  resources :users, only: [:show]
  resources :comments, except: [:show, :index]
  resources :books

  resources :clubs, except: [:destroy] do
    resources :books, only: [:index, :new, :create]
  end

  resources :books do 
    resources :comments, only: [:index, :new, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% if flash[:alert] %>
        <p><%= flash[:alert] %><p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom mt-auto py-3 text-center" style="background-color: #e3f2fd;">
  <div class="container">
    <span class="text-muted">&copy; <%= Time.current.year %> <strong>BookClub</strong></span>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;" >
  <ul class="nav">

    <li class="nav-item">
      <div class="nav-link active"><%= link_to "Home", '/' %></div>
    </li>

    <li class="nav-item">
      <div class="nav-link active"><%= link_to "About", '/about' %></div>
    </li>

    <li class="nav-item">
      <div class="nav-link active"><%= link_to "BookClubs", clubs_path %></div>
    </li>

    <% if user_signed_in? %>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <div class="dropdown-item"><%= link_to "Profile", user_path(current_user) %></div>
            <div class="dropdown-item"><%= link_to "Settings", edit_user_registration_path %></div>
            <div class="dropdown-item"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %></div>
          </div>
        </li>
    <% end %>

    <% if !user_signed_in? %>
      <li class="nav-item">
        <div class="nav-link active"><%= link_to "Sign In", new_user_session_path %></div>
      </li>
    <% end %>
    
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <br>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>